/*
  test.h
  Header file generated from parsing ISO_C_BINDING information
  from sample_005.f90.

  Generated by /home/hoel/work/code-root/github.com/berhoel/Fortran2CHeader/.direnv/python-3.14/bin/pytest, version 0.6.3.
 */

#ifndef SAMPLE_005_H
#define SAMPLE_005_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/*
  c_curvp1
  Generated from FORTRAN routine 'curvp1'
  FORTRAN declaration:
      SUBROUTINE curvp1(n, x, y, p, yp, temp, sigma, ierr) BIND(C, NAME='c_curvp1')
 */
extern void c_curvp1(const int* n, const double* x, const double* y, const double* p, double* yp, const double* temp, const double* sigma, int* ierr);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* SAMPLE_005_H */
