#
# test.pxd
# Cython Header file generated from parsing ISO_C_BINDING information
# from /home/hoel/work/code-root/github.com/berhoel/Fortran2CHeader/src/dnvgl/fortran2cheader/testing/samples/sample_004.f90.
#
# Generated by pytest, version 0.6.2.

cdef extern from "sample_004.h" nogil:
# c_curv1
# Generated from FORTRAN routine 'curv1'
# FORTRAN declaration:
#     SUBROUTINE curv1(n, x, y, slp1, slpn, islpsw, yp, temp, sigma, ierr)  BIND(C, NAME='c_curv1')
    void c_curv1(const int* n, const double* x, const double* y, const double* slp1, const double* slpn, const int* islpsw, double* yp, const double* temp, const double* sigma, int* ierr)
# c_curv2
# Generated from FORTRAN routine 'curv2'
# FORTRAN declaration:
#     FUNCTION curv2(t, n, x, y, yp, sigma) result(res) BIND(C, NAME='c_curv2')
    const double* c_curv2(const double* t, const int* n, const double* x, const double* y, const double* yp, const double* sigma)
