#
# test.pxd
# Cython Header file generated from parsing ISO_C_BINDING information
# from /home/hoel/work/code-root/github.com/berhoel/Fortran2CHeader/src/dnvgl/fortran2cheader/testing/samples/sample_005.f90.
#
# Generated by pytest, version 0.6.3.

cdef extern from "sample_005.h" nogil:
# c_curvp1
# Generated from FORTRAN routine 'curvp1'
# FORTRAN declaration:
#     SUBROUTINE curvp1(n, x, y, p, yp, temp, sigma, ierr) BIND(C, NAME='c_curvp1')
    void c_curvp1(const int* n, const double* x, const double* y, const double* p, double* yp, const double* temp, const double* sigma, int* ierr)
