/*
  test.h
  Header file generated from parsing ISO_C_BINDING information
  from sample_003.f90.

  Generated by /home/hoel/work/code-root/github.com/berhoel/Fortran2CHeader/.direnv/python-3.14/bin/pytest, version 0.6.2.
 */

#ifndef SAMPLE_003_H
#define SAMPLE_003_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/*
  pstr
  Generated from FORTRAN routine 'pstr'
  FORTRAN declaration:
      FUNCTION pstr(s) RESULT(x) BIND(c, name='pstr')
 */
extern double _Complex pstr(double _Complex s);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* SAMPLE_003_H */
