/*
  test.h
  Header file generated from parsing ISO_C_BINDING information
  from sample_001.f90.

  Generated by setup.py, version xx.
 */

#ifndef SAMPLE_001_H
#define SAMPLE_001_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/*
  pstr
  Generated from FORTRAN routine 'pstr'
  FORTRAN declaration:
      subroutine pstr(s) bind(c,name='pstr')
 */
extern void pstr(const char* s);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* SAMPLE_001_H */
