#
# test.pxd
# Cython Header file generated from parsing ISO_C_BINDING information
# from /home/hoel/work/code-root/github.com/berhoel/Fortran2CHeader/src/dnvgl/fortran2cheader/testing/samples/sample_003.f90.
#
# Generated by pytest, version 0.6.2.

cdef extern from "sample_003.h" nogil:
# pstr
# Generated from FORTRAN routine 'pstr'
# FORTRAN declaration:
#     FUNCTION pstr(s) RESULT(x) BIND(c, name='pstr')
    double _Complex pstr(double complex s)
