#
# test.pxd
# Cython Header file generated from parsing ISO_C_BINDING information
# from /home/hoel/work/code-root/github.com/berhoel/Fortran2CHeader/src/dnvgl/fortran2cheader/testing/samples/sample_006.f90.
#
# Generated by pytest, version 0.6.3.

cdef extern from "sample_006.h" nogil:
# c_surf1
# Generated from FORTRAN routine 'surf1'
# FORTRAN declaration:
#     SUBROUTINE surf1(m, n, x, y, z, iz, zx1, zxm, zy1, zyn, zxy11, zxym1, zxy1n, zxymn,  islpsw, zp, temp, sigma, ierr) BIND(C, NAME='c_surf1')
    void c_surf1(const int* m, const int* n, const double* x, const double* y, const double* z, const int* iz, const double* zx1, const double* zxm, const double* zy1, const double* zyn, const double* zxy11, const double* zxym1, const double* zxy1n, const double* zxymn, const int* islpsw, double* zp, const double* temp, const double* sigma, int* ierr)
