#
# test.pxd
# Cython Header file generated from parsing ISO_C_BINDING information
# from sample_002.f90.
#
# Generated by setup.py, version xx.

cdef extern from "sample_002.h" nogil:
# pstr
# Generated from FORTRAN routine 'pstr'
# FORTRAN declaration:
#     subroutine pstr(s) bind(c,name='pstr')
    void pstr(double complex s)
